### PR TITLE
Add a script that copies all the profiles from ceramic to Mongo

### LINKED ISSUE #41: Copy existing ceramic profiles to Mongo
Create a script that copy the data from existing ceramic profiles to our backend on mongoDB. The script should add the new profile and update the existing ones.

### PR DESCRIPTION
**Pull request by Dhaiwat10**
Closes #41 

- Run `yarn copy-ceramic-to-mongo` from the root to run the script.
- The script only displays a list of all the dev profiles for now.
- Working on adding these profiles to our DB.

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
@damianmarti  Correct me if I'm wrong: 

Now I just need to make API calls to our server's create profile endpoint to add these profiles to our DB? (and maybe also check if these profiles already exist in the DB?)

**Comment by damianmarti** [comment]
@Dhaiwat10 exactly. You have to use the server graphql create profile endpoint.

**Comment by Dhaiwat10** [comment]
For my reference: https://github.com/moonshotcollective/recruiter.party/blob/main/packages/server/services/profiles.js

**Comment by damianmarti** [comment]
@Dhaiwat10 I'm doing it while I'm doing #13. Sorry, I think we can close this PR.

**Comment by Dhaiwat10** [comment]
Cool! No problem :)

**Pull request closed without merging**
