### PR TITLE
Requests page

### LINKED ISSUE #11: Migrate requests page
Using styles from https://github.com/moonshotcollective/recruiter.party/pull/3

### PR DESCRIPTION
**Pull request by damianmarti**
closes #11 

localhost_3000_requests (2)

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
Hey @damianmarti I requested an unlock of my profile but cannot see the request: 
image

**Comment by Dhaiwat10** [comment]
^ Could this be because I haven't created my profile in the new app? 🤔

**Comment by Nazeeh21** [comment]
I'm also not getting the requests data and am seeing the same empty page as @Dhaiwat10

**Comment by damianmarti** [comment]
@Dhaiwat10 @Nazeeh21 There is a problem with the mySelf context data not keeping the value between requests (issue #39). 

I think that for this bug you are not seeing the requests. 

Please, in the requests page, try logout and login, and please let me know if then you can see the requests.

**Comment by Dhaiwat10** [comment]
@damianmarti the logout request is giving me a 404 error

**Comment by damianmarti** [comment]
@Dhaiwat10 are you running the backend server? What url is getting the 404?

**Comment by Dhaiwat10** [comment]
@damianmarti The logout request is getting a 404 in response. The React app/frontend is crashing

**Comment by damianmarti** [comment]
@Dhaiwat10 I have issues with the session cookie on Chrome. It works if I use Firefox. Which browser are you using?

**Comment by Nazeeh21** [comment]
I am using brave browser and I think @Dhaiwat10 is also using the same.

**Comment by damianmarti** [comment]
@Nazeeh21 @Dhaiwat10 please, try it on Firefox.

**Comment by Dhaiwat10** [comment]
Works fine on Firefox @damianmarti

**Review by Dhaiwat10 — APPROVED** [review]

**Pull request merged**
