### PR TITLE
Add profile page

### LINKED ISSUE #10: Migrate profile page
From the old repo using styles from https://github.com/moonshotcollective/recruiter.party/pull/2

### PR DESCRIPTION
**Pull request by damianmarti**
closes #10 

I left the UnlockProfile component for another PR.

You can access a profile page at the url http://localhost:3000/profile/[did]

For example, http://localhost:3000/profile/did:3:kjzl6cwe1jw149z5serhpr3dmdrg5h67bdwe259m2o7z7pn8d7e6cuc0stz7z0s

localhost_3000_profile_did_3_kjzl6cwe1jw149z5serhpr3dmdrg5h67bdwe259m2o7z7pn8d7e6cuc0stz7z0s (1)

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
Is there a way we can make that profile URL shorter? Looks too cluttered and long

**Review by Dhaiwat10 — APPROVED** [review]
Looks good! Awesome work @damianmarti 🚀

**Comment by Nazeeh21** [comment]
@damianmarti The PR looks good. Just one thing that  I'm getting the skills, education, and experiences as N/A. Do I need to unlock the profile to see that?
image

**Comment by Dhaiwat10** [comment]
@Nazeeh21 can you send the `.env` you are using for the server? Are you still running the server from the old repo?

**Comment by damianmarti** [comment]
> @damianmarti The PR looks good. Just one thing that I'm getting the skills, education, and experiences as N/A. Do I need to unlock the profile to see that?
> 
> image

@Nazeeh21 I think that you need a different model.json file to see that info, one linked to the schema used. I can send you this file on discord.

**Comment by damianmarti** [comment]
> Is there a way we can make that profile URL shorter? Looks too cluttered and long

Maybe we can use the tokenId instead of the did.

**Comment by Nazeeh21** [comment]
@damianmarti I've updated the `model.json` [here](https://github.com/moonshotcollective/recruiter.party/blob/feat/new-profile-page/packages/schemas/lib/model.json) and run `yarn build` in `/schemas`. Anything else I should change?

**Comment by damianmarti** [comment]
> @damianmarti I've updated the `model.json` [here](https://github.com/moonshotcollective/recruiter.party/blob/feat/new-profile-page/packages/schemas/lib/model.json) and run `yarn build` in `/schemas`. Anything else I should do because I'm seeing the same thing?

Don't run yarn build, just use the model.json I sent you. We have to check the schemas generated. I'm using the profiles saved with the old code using the schemas from the model.json file I sent you.

**Comment by QEDK** [comment]
Yes, the schemas have to be in sync to show up, if they are fine on your
end, it's probably cool. Possibily LGTM, will take a deeper look later at
night.

**Comment by Dhaiwat10** [comment]
@damianmarti I'm facing the same problem as Nazeeh. I replaced the model.json file with the file you sent on Discord but nothing changed. What am I supposed to do exactly? What steps should I follow in order to get everything setup? Thanks

**Comment by damianmarti** [comment]
> @damianmarti I'm facing the same problem as Nazeeh. I replaced the model.json file with the file you sent on Discord but nothing changed. What am I supposed to do exactly? What steps should I follow in order to get everything setup? Thanks

I pointed to the old contract address in hardhat_contracts.json to get the profiles saved there.

**Pull request merged**
