### PR TITLE
Unlock profile

### LINKED ISSUE #20: Migrate unlock profile
Migrate the UnlockProfile component from old repo.

### PR DESCRIPTION
**Pull request by damianmarti**
closes #20 

Unlock profile from profile page.

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
@damianmarti I think you should make the `UnlockProfile.jsx` file -> `UnlockProfile.tsx` since we're using TypeScript

**Comment by damianmarti** [comment]
> @damianmarti I think you should make the `UnlockProfile.jsx` file -> `UnlockProfile.tsx` since we're using TypeScript

Done!

**Comment by Dhaiwat10** [comment]
@damianmarti tried running this locally, I'm seeing this. Any idea why?

image

**Comment by Dhaiwat10** [comment]
Ok never mind it's working fine. I had to update the `model.json` file :)

**Review by Dhaiwat10 — APPROVED** [review]

**Pull request merged**
