### PR TITLE
Create `json-storage.ts`

### LINKED ISSUE #50: Migrate frontend API endpoins
https://github.com/moonshotcollective/drecruit/tree/staging/packages/react-app/pages/api

json-storage.js is used when saving the private profile to get the token uri. The Ceramic DID is saved on Web3Storage and the uri to this file is used as the tokenURI.

image-storage.js is used to save in Web3Storage the images uploaded by the users on the basic profile. 

We need to migrate this code.

### PR DESCRIPTION
**Pull request by Nazeeh21**
Fixes #50
@damianmarti I've migrated both the files from [here](https://github.com/moonshotcollective/drecruit/tree/staging/packages/react-app/pages/api) to the new repo. Other than this, is there anything else I should change?

Also, how can we use `image-storage.ts`  for image-upload and `json-storage.ts` for saving the private profile?

### CODE REVIEW

**Comment by Nazeeh21** [comment]
I'm still getting this error while saving Private profile
image

**Comment by Nazeeh21** [comment]
[This](https://github.com/moonshotcollective/recruiter.party/blob/765da8bce36eb2f6ba7d5940cba6025b67f0d470/packages/dapp/src/views/editPrivateProfile/index.tsx#L81) request is failing.

**Comment by damianmarti** [comment]
@Nazeeh21 I tested updating my private profile and it was saved successfully!

**Comment by Nazeeh21** [comment]
>  I tested updating my private profile and it was saved successfully!
that is awesome. 🥳

Lemme check it on my end as well.

**Pull request merged**
