### PR TITLE
Login and logout from server

### LINKED ISSUE #23: The user should login to the backend when connecting your account

### PR DESCRIPTION
**Pull request by damianmarti**
closes #23

### CODE REVIEW

**Review by Dhaiwat10 — APPROVED** [review]
Looks good! Thanks Damu

**Comment by damianmarti** [comment]
> Looks good! Thanks Damu

@Dhaiwat10 did you check that the session is created and the cookie saved?

**Comment by Dhaiwat10** [comment]
@damianmarti Good point. Now that I'm running it, I can't even log out. I get a 404 error when I click the log out button. Let's wait for Ankit to have a go and see what he faces lol

**Comment by damianmarti** [comment]
> @damianmarti Good point. Now that I'm running it, I can't even log out. I get a 404 error when I click the log out button. Let's wait for Ankit to have a go and see what he faces lol

Can you see the cookie saved after you login?

What url are you getting 404?

**Review by QEDK — APPROVED** [review]
LGTM!

**Pull request merged**
