### PR TITLE
Allow existing user to edit any profile without saving

### PR DESCRIPTION
**Pull request by Nazeeh21**
Fix issue #56

### CODE REVIEW

**Review by damianmarti — CHANGES_REQUESTED** [review]
Screenshot 2022-01-19 at 19-29-49 Scaffold ETH

Can you remove the upper button and add a link on the title below these?

And please change the NEXT button here to use the same style from the NEXT buttons from the other profile sections.

**Comment by Nazeeh21** [comment]
@damianmarti I've updated the styling of the `Next` button. 

But I've one doubt that these headings are getting rendered by the `chakra-UI-stepper` library. So, I don't think I can make these headings links.

image

**Comment by damianmarti** [comment]
> @damianmarti I've updated the styling of the `Next` button.
> 
> But I've one doubt that these headings are getting rendered by the `chakra-UI-stepper` library. So, I don't think I can make these headings links.
> 
> image

@Nazeeh21 you can add the link on the step setting the label to something like this:

      label: (
        <a href="/url">Public Profile</a>
      ),

**Comment by Nazeeh21** [comment]
@damianmarti Thanks for guiding me. It worked.

**Review by damianmarti — APPROVED** [review]
Nice!

**Pull request merged**
