### PR TITLE
Use new experiences and education fields on profile page

### PR DESCRIPTION
**Pull request by damianmarti**

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
@damianmarti I keep seeing this on the profile page for all profiles:

image

I'm also coming across a 404 error whenever the app loads. I am running this on Firefox.

**Comment by damianmarti** [comment]
> @damianmarti I keep seeing this on the profile page for all profiles:
> 
> image
> 
> I'm also coming across a 404 error whenever the app loads. I am running this on Firefox.

And can you see the profiles data ok on the home page?

**Comment by Nazeeh21** [comment]
image

 I'm seeing profile data on homepage

**Comment by Nazeeh21** [comment]
> image
> 
> I'm seeing profile data on homepage

I was seeing this on the deployed URL, but I'm also getting 404 network URL on localhost

**Comment by damianmarti** [comment]
> > image
> > I'm seeing profile data on homepage
> 
> I was seeing this on the deployed URL, but I'm also getting 404 network URL on localhost

I think that is missing the NEXT_PUBLIC_API_URL env var in the deployment cc/ @Dhaiwat10 

@Nazeeh21 if you go to this profile, can you see the experiences and educations fields? Have the related did profile the data saved on ceramic?

**Comment by Dhaiwat10** [comment]
@damianmarti I have the `.env` setup properly => `NEXT_PUBLIC_API_URl=http://127.0.0.1:5000`

Still doesn't work for me

**Comment by Dhaiwat10** [comment]
Nvm, I think ceramic was down. It's working now

**Pull request merged**
