### PR TITLE
Profile page

### PR DESCRIPTION
**Pull request by damianmarti**
profile1

profile2

It's not perfect but we have something to show.

### CODE REVIEW

**Review by Cali93 — APPROVED** [review]
Awesome! Looks very nice.
We just need to install the font on the dapp I think that's why it doesn't show up.

**Comment by QEDK** [comment]
Yes, just add `Inter` everything else looks good to me.

**Comment by damianmarti** [comment]
> 

@QEDK what is "Inter"?

**Comment by QEDK** [comment]
> > 
> 
> @QEDK what is "Inter"?

It's a font, it's the one Richard picked for the design system, https://fonts.google.com/specimen/Inter

**Pull request merged**
