### PR TITLE
Save profiles on MongoDB and load home profiles from MongoDB

### LINKED ISSUE #13: Save profile data in mongodb
When the user save your profile, the profile data should be saved in ceramic AND in our mongodb, using the GraphQL API.

### LINKED ISSUE #42: Retrieve the home page profiles from our backend

### PR DESCRIPTION
**Pull request by damianmarti**
closes #13 
closes #42 

Now, when the user update your public or basic profile, it's saved on MongoDB too.

The home page profiles are loaded from our backend.

Run node scripts/createNewProfiles.js from packages/server to save the current profiles on MongoDB.

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
> Run node scripts/createNewProfiles.js from packages/server to save the current profiles on MongoDB.

Wil this be a one-time thing or do we need to do this manually periodically?

**Comment by damianmarti** [comment]
> > Run node scripts/createNewProfiles.js from packages/server to save the current profiles on MongoDB.
> 
> Wil this be a one-time thing or do we need to do this manually periodically?

If you use your personal mongodb to development, you should run it periodically to update the database with the new profiles.

**Comment by Dhaiwat10** [comment]
@damianmarti What about production/staging? Do we need a cron job or just a one-time thing when we release?

**Comment by damianmarti** [comment]
> @damianmarti What about production/staging? Do we need a cron job or just a one-time thing when we release?

We can add a cron job on production/staging to update our mongodb if anyone mint a tokenId directly on the contract. And we should have an update script if any user update your ceramic profile from outside our dapp. I will create these tickets, but I think that is not so important right now.

**Review by Nazeeh21 — APPROVED** [review]
image

I created a new mongodb instance, tried creating a new profile and am able to see on the home page

**Pull request merged**
